# OpenAI API Key (required)
OPENAI_API_KEY = "your-openai-api-key"

# OCR.Space API Key (required for scanned PDFs)
OCR_SPACE_API_KEY = "your-ocr-space-api-key"

# Stripe Configuration (required for payments)
STRIPE_SECRET_KEY = "your-stripe-secret-key"
STRIPE_PAYMENT_LINK = "your-stripe-payment-link"

# App Configuration
MAX_FREE_PDFS = 1
ENVIRONMENT = "production"