# OpenAI API Key
OPENAI_API_KEY = "your-openai-api-key"

# OCR.Space API Key
OCR_SPACE_API_KEY = "your-ocr-space-api-key"

# Stripe Configuration
STRIPE_SECRET_KEY = "your-stripe-secret-key"
STRIPE_PAYMENT_LINK = "your-stripe-payment-link" 